const { buildManifestMarkdown, sanitizeFilename } = require('../electron/services/manifestExport')

const BASE_ORDER = {
  name: 'June 28 Tournament',
  lab: null,
  order_number: null,
  order_total: null,
  staged_path: null,
  session_name: null,
  notes: null
}

describe('sanitizeFilename', () => {
  test('spaces become hyphens', () => {
    expect(sanitizeFilename('June 28 Tournament')).toBe('June-28-Tournament')
  })

  test('illegal filesystem characters are replaced', () => {
    expect(sanitizeFilename('Order: Round 1/2 <Final>')).toBe('Order-Round-1-2-Final-')
  })

  test('collapses repeated hyphens and trims', () => {
    expect(sanitizeFilename('  a   b  ')).toBe('a-b')
  })
})

describe('buildManifestMarkdown', () => {
  test('formats print size as 8×10, not 8.0x10.0', () => {
    const items = [{ filename: 'photo1.jpg', print_width: 8, print_height: 10, quantity: 1, crop_applied: 0, aspect_ratio_status: 'ok' }]
    const md = buildManifestMarkdown(BASE_ORDER, items)
    expect(md).toContain('| 8×10 |')
    expect(md).not.toContain('8.0')
  })

  test('cropped items use the cropped output filename and status', () => {
    const items = [{ filename: 'photo2.jpg', print_width: 8, print_height: 10, quantity: 2, crop_applied: 1, aspect_ratio_status: 'error' }]
    const md = buildManifestMarkdown(BASE_ORDER, items)
    expect(md).toContain('photo2_8x10_cropped.jpg')
    expect(md).toContain('✓ Cropped')
  })

  test('non-cropped item status reflects aspect ratio status', () => {
    const cases = [
      ['ok', '✓ Ready'],
      ['minor', '~ Minor crop'],
      ['warn', '⚠ Crop needed'],
      ['error', '⚠ Crop needed'],
      [null, '—']
    ]
    for (const [status, expected] of cases) {
      const items = [{ filename: 'photo3.jpg', print_width: 4, print_height: 6, quantity: 1, crop_applied: 0, aspect_ratio_status: status }]
      const md = buildManifestMarkdown(BASE_ORDER, items)
      expect(md).toContain(expected)
    }
  })

  test('total prints sums quantity across items', () => {
    const items = [
      { filename: 'a.jpg', print_width: 4, print_height: 6, quantity: 2, crop_applied: 0, aspect_ratio_status: 'ok' },
      { filename: 'b.jpg', print_width: 4, print_height: 6, quantity: 3, crop_applied: 0, aspect_ratio_status: 'ok' }
    ]
    const md = buildManifestMarkdown(BASE_ORDER, items)
    expect(md).toContain('Total prints: 5')
    expect(md).toContain('2 photos · 5 prints')
  })

  test('shows a placeholder when notes are empty', () => {
    const md = buildManifestMarkdown(BASE_ORDER, [])
    expect(md).toContain('*(Add notes here)*')
  })

  test('renders real notes when present', () => {
    const order = { ...BASE_ORDER, notes: 'Placed order 9/10.' }
    const md = buildManifestMarkdown(order, [])
    expect(md).toContain('Placed order 9/10.')
    expect(md).not.toContain('*(Add notes here)*')
  })

  test('omits lab/order#/total line entirely when none are set', () => {
    const md = buildManifestMarkdown(BASE_ORDER, [])
    expect(md).not.toContain('**Lab:**')
    expect(md).not.toContain('**Order #:**')
    expect(md).not.toContain('**Total:**')
  })

  test('shows lab, order number, and total when present', () => {
    const order = { ...BASE_ORDER, lab: 'Mpix', order_number: 'MP-28847', order_total: '$34.50' }
    const md = buildManifestMarkdown(order, [])
    expect(md).toContain('**Lab:** Mpix')
    expect(md).toContain('**Order #:** MP-28847')
    expect(md).toContain('**Total:** $34.50')
  })

  test('shows session name only when order is linked to a session', () => {
    const withSession = buildManifestMarkdown({ ...BASE_ORDER, session_name: 'June 28 Session' }, [])
    expect(withSession).toContain('**Session:** June 28 Session')

    const withoutSession = buildManifestMarkdown(BASE_ORDER, [])
    expect(withoutSession).not.toContain('**Session:**')
  })

  test('includes a Generated by Frame footer with a date', () => {
    const md = buildManifestMarkdown(BASE_ORDER, [])
    expect(md).toMatch(/\*Generated by Frame · \w+ \d{1,2}, \d{4}\*/)
  })
})
