// Filename used to sanitize a print order name for use in a Markdown/PDF
// output filename — spaces become hyphens (unlike sanitizeFolderName in
// main.js's prepareFolder handler, which keeps spaces for a friendlier
// on-disk folder name).
function sanitizeFilename(name) {
  return name
    .replace(/[/\\:*?"<>|]/g, '-')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 80)
}

function statusIcon(item) {
  if (item.crop_applied) return '✓ Cropped'
  switch (item.aspect_ratio_status) {
    case 'ok': return '✓ Ready'
    case 'minor': return '~ Minor crop'
    case 'warn': return '⚠ Crop needed'
    case 'error': return '⚠ Crop needed'
    default: return '—'
  }
}

function buildManifestMarkdown(order, items) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const totalPrints = items.reduce((sum, i) => sum + i.quantity, 0)

  const rows = items.map((item, idx) => {
    const sizeTag = `${item.print_width}x${item.print_height}`
    const base = item.filename.replace(/\.[^.]+$/, '')
    const cropTag = item.crop_applied ? '_cropped' : ''
    const printName = `${base}_${sizeTag}${cropTag}.jpg`

    return `| ☐ | ${idx + 1} | ${printName} | ${sizeTag.replace('x', '×')} | ${item.quantity} | ${statusIcon(item)} |`
  }).join('\n')

  const notesSection = order.notes
    ? `\n## Order notes\n\n${order.notes}\n`
    : '\n## Order notes\n\n*(Add notes here)*\n'

  const folderLine = order.staged_path ? `**Folder:** ${order.staged_path}\n` : ''

  const labLine = [
    order.lab ? `**Lab:** ${order.lab}` : null,
    order.order_number ? `**Order #:** ${order.order_number}` : null,
    order.order_total ? `**Total:** ${order.order_total}` : null,
  ].filter(Boolean).join('  ·  ')

  return `# Print Order — ${order.name}

**Prepared:** ${now}
${labLine ? labLine + '\n' : ''}${folderLine}${order.session_name ? `**Session:** ${order.session_name}\n` : ''}
---

## Items (${items.length} photos · ${totalPrints} prints)

| ☐ | # | File | Size | Qty | Status |
|---|---|---|---|---|---|
${rows}

**Total prints: ${totalPrints}**
${notesSection}
---
*Generated by Frame · ${now}*
`
}

function buildPdfHtml(htmlBody) {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, 'Helvetica Neue', sans-serif;
    font-size: 12px;
    line-height: 1.5;
    color: #1a1a1a;
    padding: 32px 40px;
  }
  h1 {
    font-size: 20px;
    font-weight: 600;
    margin-bottom: 6px;
    color: #1a1a1a;
  }
  h2 {
    font-size: 13px;
    font-weight: 600;
    margin: 20px 0 8px;
    color: #1a1a1a;
    border-bottom: 1px solid #e0e0e0;
    padding-bottom: 4px;
  }
  p { margin-bottom: 6px; color: #333; }
  hr {
    border: none;
    border-top: 1px solid #e0e0e0;
    margin: 16px 0;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 12px;
    font-size: 11px;
  }
  th {
    background: #f5f5f5;
    padding: 6px 8px;
    text-align: left;
    font-weight: 600;
    border: 1px solid #ddd;
    white-space: nowrap;
  }
  td {
    padding: 6px 8px;
    border: 1px solid #ddd;
    vertical-align: top;
  }
  td:first-child, th:first-child {
    width: 24px;
    text-align: center;
    font-size: 14px;
  }
  td:nth-child(2), th:nth-child(2) {
    width: 28px;
    text-align: center;
    color: #999;
  }
  td:nth-child(3) {
    font-family: 'SF Mono', Menlo, monospace;
    font-size: 10px;
    color: #444;
    word-break: break-all;
  }
  td:nth-child(4), td:nth-child(5),
  th:nth-child(4), th:nth-child(5) {
    width: 60px;
    text-align: center;
  }
  tr:nth-child(even) td { background: #fafafa; }
  em { color: #888; font-style: italic; }
  strong { font-weight: 600; }
  footer {
    margin-top: 24px;
    font-size: 10px;
    color: #aaa;
    text-align: center;
  }
</style>
</head>
<body>
${htmlBody}
</body>
</html>`
}

module.exports = {
  sanitizeFilename,
  buildManifestMarkdown,
  buildPdfHtml
}
